volumes:
  valkey-data: {}

services:
  valkey:
    image: valkey/valkey:7.2-alpine
    ports:
      - 6379:6379
    volumes:
      - valkey-data:/data
    healthcheck:
      test: valkey-cli ping | grep PONG
      interval: 1s
      timeout: 3s
      retries: 10
